---
- name: libnvidia-container repo
  yum_repository:
    name: libnvidia-container
    description: libnvidia-container
    baseurl: '{{ nvidia_container_hook_repo_base_url }}{{ libnvidia_container_suffix }}'
    repo_gpgcheck: {{ libnvidia_container_repo_gpgcheck }}
    gpgcheck: {{ libnvidia_container_gpgcheck }}
    enabled: 1
    gpgkey: https://nvidia.github.io/libnvidia-container/gpgkey
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    state: present

- name: nvidia-container-runtime repo
  yum_repository:
    name: nvidia-container-runtime
    description: nvidia-container-runtime
    baseurl: '{{ nvidia_container_hook_repo_base_url }}{{ nvidia_container_runtime_suffix }}'
    repo_gpgcheck: {{ nvidia_container_runtime_repo_gpgcheck }}
    gpgcheck: {{ nvidia_container_runtime_gpgcheck }}
    enabled: 1
    gpgkey: https://nvidia.github.io/nvidia-container-runtime/gpgkey
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    state: present

- name: install nvidia-container-runtime-hook
  yum: name=nvidia-container-runtime-hook state=latest

- name: copy oci-nvidia-hook up to fast_nodes
  copy:
    src: oci-nvidia-hook
    dest: /usr/libexec/oci/hooks.d/oci-nvidia-hook
    mode: 0755

- name: sleeping for a few seconds as there seems to be a race here.
  shell: sleep 5

# # ls -alZ /dev/nvidia*                                        
# crw-rw-rw-. root root unconfined_u:object_r:xserver_misc_device_t:s0 /dev/nvidia0     
# crw-rw-rw-. root root unconfined_u:object_r:xserver_misc_device_t:s0 /dev/nvidiactl   
# crw-rw-rw-. root root unconfined_u:object_r:device_t:s0 /dev/nvidia-uvm               
# crw-rw-rw-. root root unconfined_u:object_r:device_t:s0 /dev/nvidia-uvm-tools         

- name: e2e test nvidia-container-runtime-hook integration
  shell: docker run -i --rm docker.io/mirrorgooglecontainers/cuda-vector-add:v0.1
  ignore_errors: true

- name: update SELinux type on nvidia device files
  shell: chcon -t container_file_t /dev/nvidia*

- name: e2e test nvidia-container-runtime-hook integration
  shell: docker run -i --rm docker.io/mirrorgooglecontainers/cuda-vector-add:v0.1
  ignore_errors: true
