---

- name: install kernel-devel
  yum: 
    name: kernel-devel
    state: present

- name: install EPEL
  yum: 
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm 
    state: present

- name: cuda NVIDIA repository
  yum_repository:
    name: cuda
    description: cuda
    baseurl: '{{ cuda_driver_repo_base_url }}{{ cuda_driver_repo_suffix }}'
    enabled: 1
    gpgcheck: 1
    gpgkey: http://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/7fa2af80.pub
    state: present

- name: install NVIDIA drivers
  yum:  name={{item}} state=present
  with_items:
   - nvidia-driver
   - nvidia-driver-devel
   - nvidia-driver-cuda
   - nvidia-modprobe
   - cuda-drivers

- name: load NVIDIA and unified memory kernel modules
  shell: nvidia-modprobe && nvidia-modprobe -u

- name: test drivers
  shell: nvidia-smi --query-gpu=gpu_name --format=csv,noheader --id=0
